import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/lib/queryClient";
import { UserProvider } from "@/context/user-context";
import { Navbar } from "@/components/navbar";


export const metadata: Metadata = {
  title: "CooKing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <QueryProvider>
      <UserProvider>
      <body className="mt-32"
      >
      <Navbar />
        {children}
      </body>
      </UserProvider>
    </QueryProvider>
    </html>
  );
}

