import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/lib/queryClient";


export const metadata: Metadata = {
  title: "CooKing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <QueryProvider>
      <body
      >
        {children}
      </body>
    </QueryProvider>
    </html>
  );
}

